# https://prod-20.australiaeast.logic.azure.com/workflows/80b87b8cc7114bb1a6f502e7da50a35e/triggers/manual/paths/invoke?api-version=2016-10-01&sp=/triggers/manual/run&sv=1.0&sig=c2yvrPvfjuFmbbPvjzQVWI6C3P3UahzjYh9-BHZgCtQ&size=S


openapi: 3.0.1
info:
  title: catfood
  description: ''
  version: '1.0'
servers:
  - url: https://api-ops-demo.azure-api.net/catfood
paths:
  /:
    get:
      summary: cat food1
      description: cat food1
      operationId: cat-food1
      responses:
        '200':
          description: 'null'
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]